backend:
  name: git-gateway
  branch: main
  identity:
    login: email

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: test
    label: Test
    files:
      - name: testFile
        label: Test File
        file: "src/content/test.json"
        fields:
          - { label: Title, name: title, widget: string }
